#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

define("MIGRATIONS_PATH", __DIR__."/database/migrations");
define("SEEDS_PATH", __DIR__."/database/seeds");
define("DATA_PATH", __DIR__."/database/data");

/**
 * Script for creating, destroying, and seeding the app's database
 */
class Db {

    function __construct($args)
    {
        $settings = require __DIR__ . '/config/settings.php';
        $this->args = $args;
        $capsule = new \Illuminate\Database\Capsule\Manager;
        $capsule->addConnection($settings['db']);
        $capsule->setAsGlobal();
        $capsule->bootEloquent();
    }

    function help()
    {
        echo "\n";
        echo "syntaxis: php Db <command> [<args>]".PHP_EOL;
        echo PHP_EOL;

        echo "Commands: \n";
        echo "php Db --help                  -->   Displays the help menu.".PHP_EOL;
        echo "php Db migrate                 -->   Migrate the database.".PHP_EOL;
        echo "php Db seed                    -->   Seed the database tables.".PHP_EOL;
        echo PHP_EOL;
    }

    function exec()
    {
        if (count($this->args) <= 1) {
            $this->help();
        } else {
            switch ($this->args[1]) {
                case "migrate":
                    $this->runMigrations();
                    if (!isset($this->args[2]) || $this->args[2] != '--seed')
                        break;
                case "seed":
                    $this->runSeed();
                    break;
                case "help":
                case "--help":
                    $this->help();
                    break;
            }
        }
    }

    function runMigrations()
    {
        $files = glob(MIGRATIONS_PATH.'/*.php');

        $this->run($files);
    }

    function runSeed()
    {
        $files = glob(SEEDS_PATH.'/*.php');

        $this->run($files);
    }
    
    private function run($files)
    {
        foreach ($files as $file) {
            require_once($file);

            $class = basename($file, '.php');

            $obj = new $class;
            $obj->run();
        }
    }
}

$db = new Db($argv);
$db->exec();