<style type="text/css">
    .no-margin {
        margin: 0;
    }
    .text-center {
        text-align: center;
    }
    .title {
        font-weight: bold;
    }
    .border-bottom {
        padding-bottom: 2px;
        border-bottom: 3px solid double;
        margin-top: -80px;
    }

    .logo {
        position: absolute;
        width: 60px;
        left: 40px;
        top: 40px;
    }
    .alamat {
        margin-top: 7px;
    }

</style>

<div>
    <img src="<?= $konfigurasi->base_url ?>/public/assets/images/bethesda.png" class="logo">
</div>

<div class="text-center border-bottom">
    <p class="title no-margin">YAYASAN BETHESDA SERUKAM</p>
    <h3 class="title no-margin">AKADEMI KEPERAWATAN BETHESDA SERUKAM</h3>
    <p class="alamat">
        Jalan Raya Singkawang-Bengkayang, Km 44, Kompleks RSU Bethesda Serukam, <br>
        Desa Pasti Jaya, Kecamatan Samalantan, Kab. Bengkayang, 79281 Kalimantan Barat <br>
        HP: 08990670522, e-mail: akper_bethesdaserukam@yahoo.co.id, website:http://www. akperserukam.ac.id
    </p>
</div>