<!DOCTYPE html>
<html>
<body>

    <?php include('header.phtml'); ?>

    <style type="text/css">
        .m-top {
            margin-top: 20px;
        }
        .bold {
            font-weight: bold;
        }
        .m-top-table {
            margin-top: 20px;
        }
        .pr-20 {
            padding-right: 20px;
        }
        .w-50 {
            width: 400px;
        }
        .w-100{
            width: 100px;
        }
        .w-200{
            width: 150px;
        }
        .table {
            border-collapse: collapse;
        }
        .table td, .table th{
            padding: 7px;
        }
        th {
            text-align: center;
            font-weight: bold;
            vertical-align: middle;
        }

        ul {
            list-style: decimal;
            width: 40%;
        }
        ul li .dashed {
            border-bottom: 1px solid dashed black;
            margin-bottom: 10px;
        }
        .catatan {
            font-style: italic;
            text-decoration: underline;
        }
        .mt-50 {
            margin-top: 50px;
        }
        .ml-40 {
            margin-top: 10px;
            margin-left: 50%;
            width: 200px;
        }
        .container {
            font-size: 12px;
        }

    </style>

    <div class="container">
        <div class="text-center m-top bold">
            Daftar Mahasiswa Bimbingan
        </div>

        <div class="m-top-table">
            <table>
                <tr>
                    <td>
                        <table>
                            <tr>
                                <td>Nama Dosen</td>
                                <td>:</td>
                                <td><?= $dosen_pa->karyawan->orang->nama ?? '-' ?></td>
                            </tr>
                            <tr>
                                <td>Tahun Ajaran</td>
                                <td>:</td>
                                <td><?= $dosen_pa->tahun_ajaran->nama ?? '-' ?></td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>
        </div>

        <div class="m-top-table">
            <table class="table" border="1">
                <tr>
                    <th>NO.</th>
                    <th>NIM</th>
                    <th>Nama</th>
                    <th>Tahun Ajaran</th>
                </tr>

                <?php foreach ($dosen_pa->mahasiswa_bimbingan as $key => $value): ?>
                    <tr>
                        <td style="width: 10%;"><?= $key+1 ?></td>
                        <td style="width: 35%;"><?= $value->mahasiswa->nim ?></td>
                        <td style="width: 35%;"><?= $value->mahasiswa->orang->nama ?></td>
                        <td style="width: 20%;"><?= $value->mahasiswa->tahun_ajaran->nama ?></td>
                    </tr>
                <?php endforeach ?>
                
            </table>
        </div>

    </div>

</body>
</html>