<!DOCTYPE html>
<html>
<body>

    <?php include('header.phtml'); ?>

    <style type="text/css">
        .m-top {
            margin-top: 20px;
        }
        .bold {
            font-weight: bold;
        }
        .m-top-table {
            margin-top: 20px;
        }
        .pr-20 {
            padding-right: 20px;
        }
        .w-50 {
            width: 400px;
        }
        .w-100{
            width: 100px;
        }
        .w-200{
            width: 150px;
        }
        .table {
            border-collapse: collapse;
        }
        .table td, .table th{
            padding: 7px;
            vertical-align: middle;
        }
        th {
            text-align: center;
            font-weight: bold;
            vertical-align: middle;
        }

        ul {
            list-style: decimal;
            width: 40%;
        }
        ul li .dashed {
            border-bottom: 1px solid dashed black;
            margin-bottom: 10px;
        }
        .catatan {
            font-style: italic;
            text-decoration: underline;
        }
        .mt-50 {
            margin-top: 50px;
        }
        .ml-40 {
            margin-top: 10px;
            margin-left: 50%;
            width: 200px;
        }
        .container {
            font-size: 12px;
        }

        .text-right {
            text-align: right;
        }

    </style>

    <div class="container">
        <div class="text-center m-top bold">
            Daftar Mahasiswa
        </div>

        <div class="m-top-table">
            <table class="table" border="1">
                <tr>
                    <th>Nama</th>
                    <th>Username</th>
                    <th>Password</th>
                </tr>

                <?php foreach ($pmb as $key => $value): ?>
                    <tr>
                        <td style="width: 40%;">
                            <?= $value->orang->nama ?>
                        </td>
                        <td style="width: 30%;">
                            <?= $value->orang->user->username ?>
                        </td>
                        <td style="width: 30%;">
                            <?= $value->orang->user->unenpass ?>
                        </td>
                    </tr>

                <?php endforeach ?>
                
            </table>
        </div>

    </div>

</body>
</html>